use COCO


 DECLARE @Fecha1 DATE = '2025-07-04';

 select  CCARGO_CAR COD , 41 CIA,CONVERT(VARCHAR(10), M.FECHA, 103) AS FECHA,  M.nfolio RESERV, 1 TIP, M.IDENT_CLI TERCERO, '001' SUC,
'' NAC,(CASE WHEN dbcr = 'C' THEN -1 ELSE 1 END * valor)  VALOR,
  CASE WHEN dbcr = 'C' THEN ROUND(valor , 1) ELSE 0 END AS Credito,
  CASE WHEN dbcr = 'D' THEN ROUND(valor, 1) ELSE 0 END AS Debito,
  NROHAB_HAB HAB,CONVERT(VARCHAR(10), recibocaj) RECIBO, 
nroregis TRX_NO,M.NFOLIO FACTURA, M.MOTIVO + ' ' + CAST(CCARGO_CAR AS VARCHAR) REFERENCIA, M.DBCR NOTAS,M.tcre NRO_TARJETA,
M.autor AUTORIZACION,M.FECHATRA FECHA_DE_VENC,'' FACT_ASOC,
(SELECT Max(F.CODIGO_DOCUMENTO) FROM FACTURAS F WHERE F.NFOLIO = M.NFOLIO) TIPO_DOC,
( CASE WHEN dbcr = 'D' THEN 1 ELSE -1 END * valor ) VALORME,
(SELECT Max(nombre_cli) FROM Clientes C WHERE  C.IDENT_CLI = M.IDENT_CLI) DISPLAY_NAME,M.FPAGO,M.PLAZA,
 (SELECT Max(codciud)FROM Clientes C WHERE  C.ident_cli = M.ident_cli) city,
 (SELECT Max(codpais)FROM Clientes C WHERE  C.ident_cli = M.ident_cli) country,
 (SELECT Max(telef_cli)FROM Clientes C WHERE  C.ident_cli = M.ident_cli) phone_no 
 FROM  movfolio M
 WHERE M.FECHA =@Fecha1;

 select 
 CASE 
 WHEN F.CODIGO_DOCUMENTO = 'FACTUR' THEN 'FACTURA'
 ELSE 'NCREDITO' END DOC,F.NUMERO CONS,F.FUCORTE F_FACTUR,F.FECHAANULA F_CORTE,41 CIA,
 CASE 
 WHEN F.TIPO_IDENTIFICACION = 'CE' THEN 13
 WHEN F.TIPO_IDENTIFICACION = 'CX' THEN 22
 WHEN F.TIPO_IDENTIFICACION = 'DE' THEN 42
 WHEN F.TIPO_IDENTIFICACION = 'NT' THEN 31
 WHEN F.TIPO_IDENTIFICACION = 'PA' THEN 41
 WHEN F.TIPO_IDENTIFICACION = 'TI' THEN 12
 ELSE 1  END AS TIP,
 F.IDENTIFICACION TERCERO,0 SUC,F.CIUDAD NAC,
 (SELECT MAX(M.NRESER_RES) FROM MOVFOLIO M WHERE M.NFOLIO = F.NFOLIO) AS RESERV,
 (SELECT MAX(M.CCARGO_CAR) FROM MOVFOLIO M WHERE M.NFOLIO = F.NFOLIO) AS COD,
 F.FECHAANULA FECHA_T,F.EXCLUIDOS AS VALOR,
(SELECT MAX(M.NROHAB_HAB) FROM MOVFOLIO M WHERE M.NFOLIO = F.NFOLIO) AS HAB,
 F.NFOLIO FACTURA_ASOC,'' NRO_TRX,
 (SELECT MAX(M.VOUCHE) FROM MOVFOLIO M WHERE M.NFOLIO = F.NFOLIO) RECIBO,
 F.NOMBRE NTERCERO,F.NOMBRE,1 TASADECAMBIO,'COP' TIPOMONEDA,F.DIRECCION,F.TELEFONO TEL
 from FACTURAS F
 WHERE CAST(F.FECHA AS DATE)=@Fecha1;